### PR TITLE
Switched over root index.html to Vue

### PR DESCRIPTION
**Pull request by dylantheriot**
- Added vue to root index.html
- Refactored horizontal-timeline scripts to be compatible with Vue rendering
- templated horizontal timeline using Vue
- added Readme instructions on how to add a new event to the timeline

### CODE REVIEW

**Comment by cameronbrill** [comment]
absolutely beautiful

**Comment by cameronbrill** [comment]
@dylantheriot would it be ez to make the icons and event titles hyperlinks? that way you can also see the history of our dev/design teams work ;)

**Comment by dylantheriot** [comment]
> @dylantheriot would it be ez to make the icons and event titles hyperlinks? that way you can also see the history of our dev/design teams work 😉

Yeah I was thinking about this.... I like the idea of event titles being hyperlinks (maybe?), but I think making the icons hyperlinks makes navigating the timeline unintuitive. Even the titles might make it a little confusing or weird to look at. We can talk about it more from a design/PM perspective today though :)

**Review by OneWebDev — APPROVED** [review]

**Comment by OneWebDev** [comment]
Good work on the PR, the addition of hyperlinks will be done in an additional PR.

**Pull request merged**
