### PR TITLE
Updated Live Site

### PR DESCRIPTION
**Pull request by dylantheriot**
- added schedule
- added prizes
- added discord/devpost link
- updated sponsors list

### CODE REVIEW

**Comment by cameronbrill** [comment]
I feel like there's too much space between each section. @eightants thoughts?

**Comment by eightants** [comment]
Yeah, I think vertical distance between schedule and other sections is a bit much, other than that, looks good

**Comment by dylantheriot** [comment]
I updated the spacing @cameronbrill @eightants

**Comment by eightants** [comment]
image
More vertical margin would be good on mobile here. Also, typo (should be Sunday)

**Comment by cameronbrill** [comment]
also can you copy this to /live/index.html as well? that way we have tamuhack.com/live

**Comment by dylantheriot** [comment]
- vertical margin added 
- live subfolder added

**Review by eightants — APPROVED** [review]
Looks good!

**Pull request merged**
