### PR TITLE
Switched from google forms to mailchimp

### PR DESCRIPTION
**Pull request by eightants**

### CODE REVIEW

**Comment by eightants** [comment]
Yeah, there is. Would that be the preferred implementation?

**Comment by gracekfan** [comment]
> Yeah, there is. Would that be the preferred implementation?

yes

**Comment by eightants** [comment]
Switched to embedded form field, it will still open a confirmation page once the subscribe button is clicked

**Comment by eightants** [comment]
Updated Aryan role on the page. Email signup should be complete.

**Comment by eightants** [comment]
Changes made for Edge

**Pull request merged**
